import type { Category, Brand, Product } from "@/types/product";

export const CATEGORIES: Category[] = [
  { id: "1", slug: "diagnostic", name: "Diagnostic", productCount: 128, description: "Tensiomètres, oxymètres, thermomètres" },
  { id: "2", slug: "consommables", name: "Consommables", productCount: 342, description: "Seringues, gants, compresses" },
  { id: "3", slug: "mobilier-medical", name: "Mobilier médical", productCount: 56, description: "Tables, chaises, chariots" },
  { id: "4", slug: "orthopedie", name: "Orthopédie", productCount: 94, description: "Attelles, orthèses, cannes" },
  { id: "5", slug: "premiers-secours", name: "Premiers secours", productCount: 71, description: "Trousses, défibrillateurs" },
  { id: "6", slug: "hygiene", name: "Hygiène & désinfection", productCount: 89, description: "Antiseptiques, savons, EPI" },
  { id: "7", slug: "laboratoire", name: "Laboratoire", productCount: 45, description: "Réactifs, microscopie" },
  { id: "8", slug: "reeducation", name: "Rééducation & kiné", productCount: 63, description: "Matériel de kinésithérapie" },
];

export const BRANDS: Brand[] = [
  { id: "b1", slug: "pharmatec", name: "Pharmatec", productCount: 210 },
  { id: "b2", slug: "omron", name: "Omron", productCount: 42 },
  { id: "b3", slug: "3m", name: "3M", productCount: 88 },
  { id: "b4", slug: "bd", name: "BD", productCount: 65 },
  { id: "b5", slug: "littmann", name: "Littmann", productCount: 18 },
  { id: "b6", slug: "welch-allyn", name: "Welch Allyn", productCount: 24 },
];

export const MAIN_NAV = [
  { label: "Accueil", to: "/" as const },
  { label: "Catalogue", to: "/catalogue" as const },
  { label: "Catégories", to: "/categories" as const },
  { label: "Marques", to: "/brands" as const },
  { label: "Blog", to: "/blog" as const },
  { label: "Contact", to: "/contact" as const },
];

export const FOOTER_LINKS = {
  service: [
    { label: "Aide & FAQ", to: "/faq" as const },
    { label: "Contact", to: "/contact" as const },
    { label: "Livraison", to: "/faq" as const },
    { label: "Retours & remboursements", to: "/faq" as const },
    { label: "Suivi de commande", to: "/account/orders" as const },
  ],
  legal: [
    { label: "Mentions légales", to: "/contact" as const },
    { label: "Conditions générales", to: "/contact" as const },
    { label: "Confidentialité", to: "/contact" as const },
    { label: "Cookies", to: "/contact" as const },
  ],
};

/** Mock products — remplacés par le catalogue Pharmatec au branchement backend. */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "tensiometre-omron-m3",
    name: "Tensiomètre bras Omron M3 Comfort",
    brand: "Omron",
    brandSlug: "omron",
    category: "Diagnostic",
    categorySlug: "diagnostic",
    images: [],
    price: { amount: 289000, currency: "TND" },
    compareAtPrice: { amount: 349000, currency: "TND" },
    rating: 4.7,
    ratingCount: 214,
    availability: "in_stock",
    isBestSeller: true,
    shortDescription: "Mesure clinique validée, brassard intelligent",
  },
  {
    id: "p2",
    slug: "oxymetre-pouls-pro",
    name: "Oxymètre de pouls professionnel",
    brand: "Pharmatec",
    brandSlug: "pharmatec",
    category: "Diagnostic",
    categorySlug: "diagnostic",
    images: [],
    price: { amount: 79000, currency: "TND" },
    rating: 4.5,
    ratingCount: 87,
    availability: "in_stock",
    isNew: true,
  },
  {
    id: "p3",
    slug: "stethoscope-littmann-classic",
    name: "Stéthoscope Littmann Classic III",
    brand: "Littmann",
    brandSlug: "littmann",
    category: "Diagnostic",
    categorySlug: "diagnostic",
    images: [],
    price: { amount: 620000, currency: "TND" },
    rating: 4.9,
    ratingCount: 512,
    availability: "low_stock",
  },
  {
    id: "p4",
    slug: "gants-nitrile-100",
    name: "Gants nitrile non poudrés — boîte 100",
    brand: "3M",
    brandSlug: "3m",
    category: "Consommables",
    categorySlug: "consommables",
    images: [],
    price: { amount: 34000, currency: "TND" },
    rating: 4.6,
    ratingCount: 1204,
    availability: "in_stock",
  },
  {
    id: "p5",
    slug: "thermometre-frontal-ir",
    name: "Thermomètre frontal infrarouge",
    brand: "Pharmatec",
    brandSlug: "pharmatec",
    category: "Diagnostic",
    categorySlug: "diagnostic",
    images: [],
    price: { amount: 89000, currency: "TND" },
    compareAtPrice: { amount: 119000, currency: "TND" },
    rating: 4.3,
    ratingCount: 156,
    availability: "in_stock",
  },
  {
    id: "p6",
    slug: "table-examen-inox",
    name: "Table d'examen inox — 2 sections",
    brand: "Pharmatec",
    brandSlug: "pharmatec",
    category: "Mobilier médical",
    categorySlug: "mobilier-medical",
    images: [],
    price: { amount: 1450000, currency: "TND" },
    rating: 4.4,
    ratingCount: 32,
    availability: "preorder",
  },
  {
    id: "p7",
    slug: "trousse-premiers-secours-pro",
    name: "Trousse premiers secours professionnelle",
    brand: "Pharmatec",
    brandSlug: "pharmatec",
    category: "Premiers secours",
    categorySlug: "premiers-secours",
    images: [],
    price: { amount: 129000, currency: "TND" },
    rating: 4.7,
    ratingCount: 98,
    availability: "in_stock",
    isNew: true,
  },
  {
    id: "p8",
    slug: "seringues-jetables-5ml",
    name: "Seringues jetables 5ml — pack 100",
    brand: "BD",
    brandSlug: "bd",
    category: "Consommables",
    categorySlug: "consommables",
    images: [],
    price: { amount: 42000, currency: "TND" },
    rating: 4.8,
    ratingCount: 340,
    availability: "in_stock",
  },
];
