/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PacksSlugRouteImport } from './routes/packs.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminB2bRouteImport } from './routes/admin.b2b'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountWarrantiesRouteImport } from './routes/account.warranties'
import { Route as AccountSubscriptionsRouteImport } from './routes/account.subscriptions'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountDocumentsRouteImport } from './routes/account.documents'
import { Route as AccountDashboardRouteImport } from './routes/account.dashboard'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksSlugRoute = PacksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PacksRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminB2bRoute = AdminB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWarrantiesRoute = AccountWarrantiesRouteImport.update({
  id: '/warranties',
  path: '/warranties',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSubscriptionsRoute = AccountSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDocumentsRoute = AccountDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDashboardRoute = AccountDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/packs': typeof PacksRouteWithChildren
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/documents': typeof AccountDocumentsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/account/warranties': typeof AccountWarrantiesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/b2b': typeof AdminB2bRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/packs/$slug': typeof PacksSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/packs': typeof PacksRouteWithChildren
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/documents': typeof AccountDocumentsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/account/warranties': typeof AccountWarrantiesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/b2b': typeof AdminB2bRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/packs/$slug': typeof PacksSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/categories': typeof CategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/packs': typeof PacksRouteWithChildren
  '/search': typeof SearchRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/dashboard': typeof AccountDashboardRoute
  '/account/documents': typeof AccountDocumentsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/subscriptions': typeof AccountSubscriptionsRoute
  '/account/warranties': typeof AccountWarrantiesRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/b2b': typeof AdminB2bRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/packs/$slug': typeof PacksSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/advisor'
    | '/auth'
    | '/cart'
    | '/catalogue'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/packs'
    | '/search'
    | '/account/addresses'
    | '/account/dashboard'
    | '/account/documents'
    | '/account/notifications'
    | '/account/orders'
    | '/account/profile'
    | '/account/subscriptions'
    | '/account/warranties'
    | '/account/wishlist'
    | '/admin/b2b'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/packs/$slug'
    | '/product/$slug'
    | '/account/'
    | '/admin/'
    | '/blog/'
    | '/brands/'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/auth'
    | '/cart'
    | '/catalogue'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/packs'
    | '/search'
    | '/account/addresses'
    | '/account/dashboard'
    | '/account/documents'
    | '/account/notifications'
    | '/account/orders'
    | '/account/profile'
    | '/account/subscriptions'
    | '/account/warranties'
    | '/account/wishlist'
    | '/admin/b2b'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/packs/$slug'
    | '/product/$slug'
    | '/account'
    | '/admin'
    | '/blog'
    | '/brands'
    | '/categories'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/advisor'
    | '/auth'
    | '/cart'
    | '/catalogue'
    | '/checkout'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/packs'
    | '/search'
    | '/account/addresses'
    | '/account/dashboard'
    | '/account/documents'
    | '/account/notifications'
    | '/account/orders'
    | '/account/profile'
    | '/account/subscriptions'
    | '/account/warranties'
    | '/account/wishlist'
    | '/admin/b2b'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/packs/$slug'
    | '/product/$slug'
    | '/account/'
    | '/admin/'
    | '/blog/'
    | '/brands/'
    | '/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdvisorRoute: typeof AdvisorRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CatalogueRoute: typeof CatalogueRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PacksRoute: typeof PacksRouteWithChildren
  SearchRoute: typeof SearchRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$slug': {
      id: '/packs/$slug'
      path: '/$slug'
      fullPath: '/packs/$slug'
      preLoaderRoute: typeof PacksSlugRouteImport
      parentRoute: typeof PacksRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/b2b': {
      id: '/admin/b2b'
      path: '/b2b'
      fullPath: '/admin/b2b'
      preLoaderRoute: typeof AdminB2bRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/warranties': {
      id: '/account/warranties'
      path: '/warranties'
      fullPath: '/account/warranties'
      preLoaderRoute: typeof AccountWarrantiesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/subscriptions': {
      id: '/account/subscriptions'
      path: '/subscriptions'
      fullPath: '/account/subscriptions'
      preLoaderRoute: typeof AccountSubscriptionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/documents': {
      id: '/account/documents'
      path: '/documents'
      fullPath: '/account/documents'
      preLoaderRoute: typeof AccountDocumentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/dashboard': {
      id: '/account/dashboard'
      path: '/dashboard'
      fullPath: '/account/dashboard'
      preLoaderRoute: typeof AccountDashboardRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountDashboardRoute: typeof AccountDashboardRoute
  AccountDocumentsRoute: typeof AccountDocumentsRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSubscriptionsRoute: typeof AccountSubscriptionsRoute
  AccountWarrantiesRoute: typeof AccountWarrantiesRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountDashboardRoute: AccountDashboardRoute,
  AccountDocumentsRoute: AccountDocumentsRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSubscriptionsRoute: AccountSubscriptionsRoute,
  AccountWarrantiesRoute: AccountWarrantiesRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminB2bRoute: typeof AdminB2bRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminB2bRoute: AdminB2bRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PacksRouteChildren {
  PacksSlugRoute: typeof PacksSlugRoute
}

const PacksRouteChildren: PacksRouteChildren = {
  PacksSlugRoute: PacksSlugRoute,
}

const PacksRouteWithChildren = PacksRoute._addFileChildren(PacksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdvisorRoute: AdvisorRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CatalogueRoute: CatalogueRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PacksRoute: PacksRouteWithChildren,
  SearchRoute: SearchRoute,
  BlogSlugRoute: BlogSlugRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
